repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [ --allow-multiple-documents ]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: no-commit-to-branch

  - repo: https://github.com/jguttman94/pre-commit-gradle
    rev: v0.3.0
    hooks:
      - id: gradle-check
        args: [ "-w" ]
      - id: gradle-spotless
        args: [ "-w" ]

#  - repo: https://github.com/commitizen-tools/commitizen
#    rev: v3.2.2
#    hooks:
#      - id: commitizen

#  - repo: local
#    hooks:
#      - id: script
#        name: script
#        entry: script.sh
#        language: script
#        pass_filenames: false
