version: '3.8'
services:
#  db:
#    image: postgres:latest
#    restart: always
#    environment:
#      - POSTGRES_USER=race_planner
#      - POSTGRES_PASSWORD=RacingPlanner!2
#    ports:
#      - '5432:5432'
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    deploy:
#      resources:
#        limits:
#          cpus: '2'
#          memory: 1024M
  api:
    build: .
#    environment:
#      - UI_ORIGIN=http://localhost:9000
#      - DATABASE_URL=postgres://race_planner:RacingPlanner!2@db/race_planner
#      - RUST_LOG=debug
    ports:
      - '3000:80'
      - '3001:8080'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
#    depends_on:
#      - db
volumes:
  db-data:



#version: '2'
#
#services:
#  app:
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      dockerfile: Dockerfile-spring
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#  db:
#    image: 'postgres:15.3-alpine'
#    container_name: db
#    environment:
#      - POSTGRES_USER=compose-postgres
#      - POSTGRES_PASSWORD=compose-postgres

